---
include:
  - "**/*.rb"
exclude:
  - "**/spec/**/*"
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
plugins:
  - solargraph-rspec
  - solargraph-rails
rspec:
  let_methods:
    - let_it_be
  example_methods:
    - my_example
reporters:
  - typecheck:strict
  - rubocop
  - require_not_found
formatter:
  rubocop:
    cops: all
max_files: 20000
