---
include:
  - "**/*.rb"
exclude:
  - "**/spec/**/*"
  - test/**/*
  - ".bundle/**/*"
require: []
domains: []
plugins:
  - solargraph-rspec
  - solargraph-rails
rspec:
  let_methods:
    - let_it_be
  example_methods:
    - my_example
reporters:
  - rubocop
  - require_not_found
max_files: 20000
