alias gcofzf='git checkout $(git branch --all | fzf)'
alias gcobfzf='git checkout -b $(git branch --all | fzf)'
alias gcob='git checkout -b'
alias mkdir='mkdir -p'
alias gdb='git diff origin/main..HEAD'
